version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-money-transfer-demo
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  wiremock:
    image: wiremock/wiremock
    container_name: wiremock
    ports:
      - "8082:8080"
    volumes:
      - ./mocks/:/home/wiremock/
volumes:
  postgres_data:
    driver: local