version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-money-transfer-demo
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - money_transfer_demo_postgres_data:/var/lib/postgresql/data
      - ./create-database.sql:/docker-entrypoint-initdb.d/create_database.sql
  wiremock:
    image: wiremock/wiremock
    container_name: wiremock
    ports:
      - "8082:8080"
    volumes:
      - ./mocks/:/home/wiremock/
  money-transfer-service:
    container_name: money-transfer-service
    build:
      context: ../
    image: money-transfer-demo
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/money_transfer_demo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      AUTHORIZATION_SERVICE_URL: http://wiremock:8080
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - wiremock
volumes:
  money_transfer_demo_postgres_data:
    driver: local